@startuml
start
:идёшь по улице;
:увидел под ногами 50 рублей;
if (поднять?) then (да)
:ты сказочно богат;
start
:моральные муки;
else (нет)
:всё так же беден;
start
:принял правильное решение;
endif
:начинаю голодать;
:голодаю;
:голодная смерть;
end
@enduml